services:
  - type: static_site
    name: visionshop-frontend
    env: static
    branch: main
    buildCommand: cd frontend && npm install --include=dev && npm run build
    publishPath: frontend/dist
  - type: web_service
    name: visionshop-backend
    env: node
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
